apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource
  name: spring-boot-petclinic
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-petclinic-complete
  ports:
    - protocol: TCP
      port: 8084 # The port the service is running on in the clustor
      targetPort: 8084 # The port exposed by the service